/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:a3051d94-75b5-4a59-8ee0-02c2e86cfbfa",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_ShtoqUYq3",
    "aws_user_pools_web_client_id": "3b7l0nir6ov7n25dvmogvjvrh0",
    "oauth": {},
    "aws_user_files_s3_bucket": "geekdatingapp96f59a704d5e4cf6ac30f4614f87402b121209-dev",
    "aws_user_files_s3_bucket_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://7klmhvgqsrfjjn2blb5gbry2em.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
